apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Hepsiburada
  description: Hepsiburada
  links:
    - url: http://www.hepsiburada.com/
      title: Website
    - url: https://redme.hepsiburada.com/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Hepsiburada
    email: sefa.pehlivan@hepsiburada.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [devx]
---
# # apiVersion: backstage.io/v1alpha1
# # kind: Location
# # metadata:
# #   name: example-groups
# #   description: A collection of all Backstage example Groups
# # spec:
# #   targets:
# #     - ./infrastructure-group.yaml
# #     - ./boxoffice-group.yaml
# #     - ./backstage-group.yaml
# #     - ./team-a-group.yaml
# #     - ./team-b-group.yaml
# #     - ./team-c-group.yaml
# #     - ./team-d-group.yaml
# ---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devx
  description: DevX
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: devx@hepsiburada.com
    #picture: https://avatars.dicebear.com/api/identicon/devx@example.com.svg?background=%23fff&margin=25
  parent: Hepsiburada
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vahit.ustaoglu
spec:
  profile:
    userName: vustaoglu
    displayName: Vahit Ustaoğlu
    email: vahit.ustaoglu@hepsiburada.com
    picture: https://gitlab.hepsiburada.com/api/api/v4/avatar?email=vahit.ustaoglu@hepsiburada.com&size=32
  memberOf: [devx]
---
